require('circular') # for handling circular data
require('CircMLE') # for Maximum Likelihood Estimation of bimodal models
# Generate a sample for plotting
angles = rvonmises(n = 20, #20 points
                   mu = circular(-30, # mean at 30° to the left
                                 units = 'degrees',
                                 rotation = 'clock'), 
                   kappa = A1inv(0.80),#mean vector length approx. 0.8
                   control.circular = list(units = 'degrees',
                                           rotation = 'clock')
                   )

# Set up plotting function
PCfun = function(angles,
                 col,
                 shrink = 1.5,
                 title = '',
                 side = 1)
{
  ca = circular(x = angles,
                units = 'degrees',
                rotation = 'clock')
  plot.circular(x = ca,
                col = col,
                stack = TRUE,
                sep = 0.1,
                bins = 355/5,
                units = 'degrees',
                rotation = 'clock',
                zero = pi/2,
                shrink = shrink)
  mtext(text = title,
        side = side,
        line = -2)
  lines(x = c(0,0),
        y = c(-1,1),
        col = 'gray')
  arrows.circular(x = mean.circular(ca),
                  y = rho.circular(ca),
                  zero = pi/2,
                  rotation = 'clock',
                  col = col,
                  length =0.1)
}

#Probability density plotting
PlotDvm = function(mu, #mean (in degrees clockwise from top)
                   kappa, #concentration parameter
                   radius = 1.15, #radius to plot at (1 = edge of circle)
                   col = 'salmon', #line colour
                   lwd = 2, #line width
                   ...) #passed to lines
{
  xx = seq(from = -180, to  = 180, by = 0.1) #sequence of angles
  #calculate probability density at each angle
  dd = dvonmises(x = circular(xx,
                              units = 'degrees',
                              rotation = 'clock'
                              ),
                 mu = mu, # circular format (if generated by mle.vonmises)
                 kappa = kappa)
  lines(x = sin(rad(xx)) * (dd +radius), #x = sin(a), y = cos(a) rotates clockwise from top
        y = cos(rad(xx)) * (dd +radius),
        col = col,
        lwd = lwd,
        ...)
    
}

#Probability density plotting for a mixture distribution
PlotDmixvm = function(mu1, #mean (in degrees clockwise from top)
                   kappa1, #concentration parameter
                   mu2 = NA, #mean (in degrees clockwise from top)
                   kappa2 = NA, #concentration parameter
                   prop = 1.0, #proportion around mean 1
                   radius = 1.15, #radius to plot at (1 = edge of circle)
                   col = 'salmon', #line colour
                   lwd = 2, #line width
                   ...) #passed to lines
{
  xx = seq(from = -180, to  = 180, by = 0.1)
  dd = dmixedvonmises(x = circular(xx,
                              units = 'degrees',
                              rotation = 'clock'
                              ),
                      mu1 = mu1, # should be circular format (may not be if generated by circ_mle)
                      kappa1 = kappa1,
                      prop = if(is.na(mu2)){1.0}else{prop}, #only include a 2nd distribution if there is a 2nd mean
                      mu2 = if(is.na(mu2)){0.0}else{mu2}, # should be circular format (may not be if generated by circ_mle)
                      kappa2 = if(is.na(mu2)){0.0}else{kappa2}
                      )
  lines(x = sin(rad(xx)) * (dd +radius), #x = sin(a), y = cos(a) rotates clockwise from top
        y = cos(rad(xx)) * (dd +radius),
        col = col,
        lwd = lwd,
        ...)
    
}


# Fit Maximum Likelihood von MIses ----------------------------------------
ml_vm = mle.vonmises(x = angles,
                     bias = TRUE)# correct for small sample biases
print(ml_vm)



# Plot data ---------------------------------------------------------------
#plot the raw data and their mean vector
PCfun(angles = angles,
      col = 'darkblue',
      title = 'simulated angles')

#plot the probability density of the fitted von Mises distribution
with(ml_vm, #using variables stored in ml_vm
     {
      PlotDvm(mu = mu, 
              kappa = kappa,
              radius = 1.05
              )
     }
)


# Add a 2nd mean opposite --------------------------------------------------
#generate more observations for a 2nd mean
angles2 = with(ml_vm, #using variables stored in ml_vm
     {
      rvonmises(n = 10, #Only 10 points this time, so 1/3 of all observations
                    mu = circular(mu +180, # same mean +180°
                                  units = 'degrees',
                                  rotation = 'clock'), 
                    kappa = kappa,#same concentration
                    control.circular = list(units = 'degrees',
                                            rotation = 'clock')
                )
     }
)

#plot the new sample in a new colour
points.circular(angles2,
                col = 'darkgreen',
                stack = TRUE,
                sep = 0.1,
                bins = 355/5,
                zero = pi/2
                )


# Combine samples ---------------------------------------------------------
all_angles = c(angles, angles2)

#plot together
PCfun(angles = all_angles,
      col = 'cyan4',
      title = 'combined sample')


# Fit maximum likelihood bimodal model -----------------------------------
#fit a variety of circular models to find the best
cmle = circ_mle(data = all_angles)#this takes a while!

#inspect the results (best model automatically at the top)
#q1 is mean 1 in radians
#q2 is mean 2 in radians
#k1 is concentration for mean 1
#k2 is concentration for mean 2
#"lamda" [sic] is the relative proportion of observations around mean 1 (on a scale of 0.0 to 1.0)

print(
  cmle$results[ ,#all rows
                    c(1:7, # parameters
                       12) # AIC (lower is better)
                    ]
      )
#M1 is uniform
#M2 is unimodal (von Mises distribution)
#M3 - M5  are bimodal (mixture of two von Mises distributions)

#extract the parameters of the "best" model (most likely, lowest AIC, simplest)
best_model = with(cmle,
                  {
                    mod_names = rownames(results) #find the names of all models
                    bm = results[mod_names%in% bestmodel, ] #extract the results row for the best one
                    return(bm)
                    }
                  )


# Plot each distribution component ----------------------------------------

with(best_model, #using variables stored in best_model
     { # make sure mu is in "circular" format
       PlotDvm(mu = circular(deg(q1), #this was in radians, convert to degrees 
                             units = 'degrees',
                             rotation = 'clock'),
               kappa = k1,
               radius = 1.05,
               col = 'darkblue'
       )
     }
)

with(best_model, #using variables stored in best_model
     { # make sure mu is in "circular" format
       PlotDvm(mu = circular(deg(q2), #this was in radians, convert to degrees 
                             units = 'degrees',
                             rotation = 'clock'),
               kappa = k2,
               radius = 1.05,
               col = 'darkgreen'
       )
     }
)


# Plot their combination --------------------------------------------------
#plot together
PCfun(angles = all_angles,
      col = 'cyan4',
      title = 'combined sample')

with(best_model, #using variables stored in best_model
     { # make sure mu is in "circular" format
       PlotDmixvm(mu1 = circular(deg(q1), #this was in radians, convert to degrees 
                             units = 'degrees',
                             rotation = 'clock'),
                  mu2 = circular(deg(q2), #this was in radians, convert to degrees 
                             units = 'degrees',
                             rotation = 'clock'),
               kappa1 = k1,
               kappa2 = k2,
               prop = lamda,#spelled incorrectly in circMLE!
               radius = 1.05,
               col = 'salmon'
       )
     }
)



